# Generated by Django 5.2.5 on 2025-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField()),
                ('text1', models.TextField()),
                ('title2', models.TextField()),
                ('text2', models.TextField()),
                ('title3', models.TextField()),
                ('text3', models.TextField()),
                ('title4', models.TextField()),
                ('text4', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
