# Generated by Django 5.2.5 on 2025-08-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='about_us',
        ),
    ]
