# Generated by Django 5.2.5 on 2025-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_rename_about_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
