# Generated by Django 5.2.5 on 2025-08-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_categories_products_slug_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='best_sells',
        ),
    ]
