# Generated by Django 5.2.5 on 2025-08-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0006_delete_best_sells'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pulse.products')),
            ],
        ),
    ]
