# Generated by Django 5.2.5 on 2025-08-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
