# Generated by Django 5.2.5 on 2025-08-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0011_message_rename_body_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
