# Generated by Django 5.2.5 on 2025-08-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0012_rename_comment_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
