# Generated by Django 5.2.5 on 2025-08-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_rename_comment_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
