# Generated by Django 5.2.5 on 2025-09-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0016_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
